// Catálogo mock utilizado tanto para la API REST como para simular el backend GraphQL
const mockRecipes = [
  {
    id: '1',
    title: 'Tiramisú clásico',
    category: 'Postre',
    difficulty: 'Intermedio',
    cookTime: 45,
    servings: 8,
    shortDescription: 'Un postre italiano con capas de queso mascarpone y café fuerte.',
    ingredients: [
      '500 g de queso mascarpone frío',
      '4 huevos frescos',
      '100 g de azúcar',
      '400 g de bizcotelas o vainillas',
      '2 tazas de café espresso frío',
      '2 cdas de licor amaretto (opcional)',
      'Cacao amargo para espolvorear',
    ],
    steps: [
      'Separar claras y yemas. Batir las yemas con el azúcar hasta lograr una mezcla pálida.',
      'Incorporar el mascarpone frío a las yemas con movimientos envolventes.',
      'Batir las claras a punto nieve y sumarlas a la crema de mascarpone.',
      'Mezclar el café con el amaretto y remojar rápidamente las vainillas.',
      'Armar capas de vainillas y crema en una fuente. Refrigerar al menos 4 horas.',
      'Servir espolvoreando cacao amargo justo antes de llevar a la mesa.',
    ],
    image: 'https://www.haceloconhuevos.com/wp-content/uploads/2022/02/Tiramisu%CC%81-cla%CC%81sico.jpg',
  },
  {
    id: '2',
    title: 'Ramen casero de pollo',
    category: 'Plato principal',
    difficulty: 'Intermedio',
    cookTime: 70,
    servings: 4,
    shortDescription: 'Caldo profundo con fideos, pollo dorado y huevo marinado.',
    ingredients: [
      '2 pechugas de pollo con piel',
      '250 g de fideos para ramen',
      '1 litro de caldo de pollo',
      '2 cdas de salsa de soya',
      '1 cda de miso suave',
      '2 huevos cocidos en 7 minutos',
      '1 diente de ajo y un trozo de jengibre',
      'Cebollín y aceite de sésamo para terminar',
    ],
    steps: [
      'Dorar el pollo con piel hacia abajo hasta obtener un crujiente dorado. Reservar.',
      'Saltear ajo y jengibre, desglasar con salsa de soya y añadir el caldo.',
      'Cocinar el pollo dentro del caldo 20 minutos. Retirar, cortar en lonjas y reservar.',
      'Incorporar el miso sin que hierva. Ajustar sal.',
      'Cocer los fideos según envase y servir con caldo caliente, pollo, huevo y cebollín.',
    ],
    image: 'https://cocinista.b-cdn.net/download/bancorecursos/recetas/receta-ramen-pollo.jpg',
  },
  {
    id: '3',
    title: 'Ensalada mediterránea',
    category: 'Entrada',
    difficulty: 'Fácil',
    cookTime: 20,
    servings: 2,
    shortDescription: 'Tomates jugosos, queso feta y aceitunas en un dressing de limón.',
    ingredients: [
      '2 tomates grandes maduros',
      '1 pepino en rodajas',
      '1/2 cebolla morada en pluma',
      '100 g de queso feta en cubos',
      '12 aceitunas kalamata',
      'Jugo de 1 limón y 3 cdas de aceite de oliva',
      'Orégano seco, sal y pimienta',
    ],
    steps: [
      'Cortar los vegetales en trozos medianos y disponer en una fuente.',
      'Batir jugo de limón, aceite, orégano, sal y pimienta hasta emulsionar.',
      'Mezclar los vegetales con el dressing y coronar con feta y aceitunas.',
      'Servir de inmediato para mantener el crocante del pepino.',
    ],
    image: 'https://comedera.com/wp-content/uploads/sites/9/2024/10/ensalada-mediterranea-de-tomate-aceitunas-y-queso-feta.jpg?fit=1316,877&crop=0px,69px,1316px,740px',
  },
  {
    id: '4',
    title: 'Brownies húmedos de chocolate',
    category: 'Postre',
    difficulty: 'Fácil',
    cookTime: 35,
    servings: 12,
    shortDescription: 'Brownies con centro fudgy y costra brillante de cacao.',
    ingredients: [
      '200 g de chocolate amargo',
      '150 g de mantequilla',
      '3 huevos',
      '200 g de azúcar',
      '90 g de harina sin polvos',
      '40 g de cacao amargo',
      '1 pizca de sal y vainilla',
    ],
    steps: [
      'Derretir chocolate con mantequilla a baño maría y templar.',
      'Batir huevos con azúcar hasta que espesen y se aclaren.',
      'Incorporar el chocolate fundido y luego los secos tamizados.',
      'Verter en molde cuadrado y hornear a 180°C por 22-25 minutos.',
      'Enfriar completamente antes de cortar para lograr bordes firmes y centro húmedo.',
    ],
    image: 'https://www.lambonadasdegalicia.club/wp-content/uploads/2022/03/brownie-humedo-scaled.jpg',
  },
  {
    id: '5',
    title: 'Salmón al horno con miel y mostaza',
    category: 'Plato principal',
    difficulty: 'Fácil',
    cookTime: 30,
    servings: 4,
    shortDescription: 'Filetes jugosos con glaseado dulce y acidulado listo en media hora.',
    ingredients: [
      '4 filetes de salmón con piel',
      '2 cdas de miel',
      '1 cda de mostaza de Dijon',
      '1 cda de jugo de limón',
      '1 diente de ajo rallado',
      'Sal, pimienta y eneldo fresco',
    ],
    steps: [
      'Precalentar el horno a 200°C y forrar una bandeja con papel antiadherente.',
      'Mezclar miel, mostaza, limón, ajo, sal y pimienta hasta obtener un glaseado.',
      'Colocar el salmón con la piel hacia abajo, pincelar con el glaseado.',
      'Hornear 12-14 minutos según grosor hasta que el centro esté jugoso.',
      'Terminar con eneldo fresco y servir con vegetales asados.',
    ],
    image: 'https://www.lacocinadealigator.com/clients/lacocinadealigator/food/recipe/images/72_details.jpg',
  },
  {
    id: '6',
    title: 'Curry cremoso de garbanzos',
    category: 'Vegetariano',
    difficulty: 'Intermedio',
    cookTime: 40,
    servings: 4,
    shortDescription: 'Curry suave con leche de coco, especias y garbanzos dorados.',
    ingredients: [
      '2 tazas de garbanzos cocidos',
      '1 cebolla en cubos finos',
      '2 cdas de pasta de curry amarillo',
      '1 taza de leche de coco',
      '1 tomate maduro picado',
      '1 cda de jengibre rallado',
      'Cilantro fresco y arroz jazmín para acompañar',
    ],
    steps: [
      'Saltear cebolla con aceite hasta transparentar, añadir jengibre y pasta de curry.',
      'Sumar tomate y cocinar 5 minutos hasta que se desarme.',
      'Agregar garbanzos y dorar ligeramente en las especias.',
      'Verter la leche de coco y cocinar a fuego bajo 15 minutos. Ajustar sal.',
      'Servir con arroz jazmín y hojas de cilantro fresco.',
    ],
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=1200&q=80',
  },
  {
    id: '7',
    title: 'Pan de masa madre express',
    category: 'Panadería',
    difficulty: 'Avanzado',
    cookTime: 180,
    servings: 1,
    shortDescription: 'Pan crujiente con corteza rústica usando un prefermento rápido.',
    ingredients: [
      '120 g de masa madre activa',
      '380 g de harina panadera',
      '300 ml de agua tibia',
      '9 g de sal',
      '1 cda de miel para acelerar la fermentación',
      'Semolina para espolvorear el banneton',
    ],
    steps: [
      'Mezclar masa madre, agua y miel. Incorporar la harina y reposar 30 minutos (autólisis).',
      'Agregar sal y realizar pliegues cada 20 minutos durante 1 hora.',
      'Reposar hasta que duplique volumen (1-2 horas según temperatura).',
      'Formar una bola tensa, colocar en banneton enharinado y fermentar 45 minutos.',
      'Hornear en olla de hierro a 240°C: 20 minutos tapado y 20 destapado hasta dorar.',
    ],
    image: 'https://nereazorokiaingarin.com/wp-content/uploads/2020/01/NHI0144-1536x1536.jpeg',
  },
  {
    id: '8',
    title: 'Tacos de pescado con repollo y lima',
    category: 'Plato principal',
    difficulty: 'Fácil',
    cookTime: 30,
    servings: 4,
    shortDescription: 'Filetes de pescado especiados en tortillas con salsa cremosa de yogur.',
    ingredients: [
      '500 g de pescado blanco en tiras',
      '1 cda de pimentón ahumado y 1 cdita de comino',
      'Jugo y ralladura de 1 lima',
      '8 tortillas de maíz',
      '1 taza de repollo morado finamente picado',
      '1/2 taza de yogur natural',
      'Cilantro y salsa picante al gusto',
    ],
    steps: [
      'Marinar el pescado con especias, sal y la mitad del jugo de lima por 15 minutos.',
      'Cocinar en sartén caliente con poco aceite 2-3 minutos por lado.',
      'Mezclar yogur con el resto del jugo de lima y ralladura para la salsa.',
      'Calentar las tortillas y armar tacos con pescado, repollo, salsa y cilantro.',
    ],
    image: 'https://okdiario.com/img/2024/08/21/tacos-de-pescado-con-ensalada-de-col-y-salsa-de-yogur-635x358.jpg',
  },
  {
    id: '9',
    title: 'Smoothie verde energizante',
    category: 'Bebida',
    difficulty: 'Fácil',
    cookTime: 10,
    servings: 2,
    shortDescription: 'Batido cremoso con espinaca, manzana verde y proteína vegetal.',
    ingredients: [
      '1 taza de espinacas frescas',
      '1 manzana verde en cubos',
      '1/2 plátano congelado',
      '1 taza de leche de almendras',
      '1 cda de mantequilla de almendras',
      '1 scoop de proteína vegetal (opcional)',
      'Hielo al gusto',
    ],
    steps: [
      'Colocar todos los ingredientes en la licuadora empezando por los líquidos.',
      'Procesar a máxima potencia hasta obtener una mezcla cremosa y sin trozos.',
      'Agregar hielo si se quiere más espeso y volver a batir.',
      'Servir de inmediato para aprovechar los nutrientes.',
    ],
    image: 'https://www.selfprotein.com/wp-content/uploads/2024/09/green-energy-smoothie.png',
  },
];

export default mockRecipes;
